### PR TITLE
Version and changelog updates for 0.7.0

### PR DESCRIPTION
**Pull request by tofay**
Housekeeping help for next release, per https://github.com/softprops/shiplift/issues/235#issuecomment-762417706

### CODE REVIEW

**Comment by softprops** [comment]
😍 thank you so much for putting this together. I'll try and cut a new release this week

**Comment by tofay** [comment]
> 
> 
> 😍 thank you so much for putting this together. I'll try and cut a new release this week

You're welcome, and thanks in advance!

**Comment by rakshith-ravi** [comment]
Hey. Now that this is merged, can we release 0.7 please?

**Comment by tofay** [comment]
@softprops please can you cut a release?

**Comment by softprops** [comment]
Done

**Comment by tofay** [comment]
> 
> 
> Done

Thank you!

**Pull request merged**
