### PR TITLE
Update container.rs

### PR DESCRIPTION
**Pull request by rakshith-ravi**
## What did you implement:

Added name filter to list containers

## How did you verify your change:

Ran it on my system, but shouldn't be too big of a change to not work on any other machine.

## What (if anything) would need to be called out in the CHANGELOG for the next release:

We can now filter containers by the name of the container.

## PS

Would appreciate releasing this in a new release. We kinda need to use this for an application that we're using.

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Hi,
this PR has some issues:

* Please squash the commits. There's really just one thing you're changing here
* Please update the commit message to something more reasonable

**Comment by rakshith-ravi** [comment]
@softprops done

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Thanks for squashing. Please remove the merge commit.

**Comment by rakshith-ravi** [comment]
Okay I've messed it up even more. Let me try this again :sweat_smile:

**Comment by rakshith-ravi** [comment]
Fingers crossed this time it's fine

**Review by matthiasbeyer — APPROVED** [review]
:tada:

**Comment by matthiasbeyer** [comment]
Yay, thank you very much for your contribution! I hope you come back to contribute more! :heart:

**Comment by rakshith-ravi** [comment]
I'd love to! I wanted to take up #291 sometime and see if I can implement that. Any pointers on how to make it?

**Pull request merged**
