### PR TITLE
[WIP] Expose port

### PR DESCRIPTION
**Pull request by sharksforarms**

### CODE REVIEW

**Comment by Nurrl** [comment]
Hi @sharksforarms, I'll rapidly need this feature. Can I help you in any way ? :D

**Comment by softprops** [comment]
@sharksforarms there have been recent changes that introduced merge conflicts here. What is the current status of this branch?

**Comment by Nurrl** [comment]
@sharksforarms Can I merge it into my fork, resolve the conflict and submit a new pull request ?

**Comment by Nurrl** [comment]
Also why Travis is failing when building openssl ?

**Comment by softprops** [comment]
Not sure about openssl. Try to sync with the lastest master and see if you get the same result

**Comment by Nurrl** [comment]
@softprops Can you explain why there is all theses:
```rust
    params_list: HashMap<&'static str, Vec<String>>,
    params_hash: HashMap<String, Vec<HashMap<String, String>>>,
```
why the `params: HashMap<&'static str, Value>,` isn't enought ?

**Comment by Nurrl** [comment]
@softprops, using the macro `json!()`, we can get rid of `params_list` and `param_hash`. I'm currently testing it alone and it seems to work well :D

**Comment by softprops** [comment]
closing this in favor of the now merged https://github.com/softprops/shiplift/pull/127

**Comment by Nurrl** [comment]
Can be closed @softprops.

**Pull request closed without merging**
